### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ame57** [adafruit/Adafruit_CircuitPython_INA219#27]
Hello! After installing the required libraries, I always get the following attribute error when runnin the example file:

i2c_bus = board.I2C()

AttributeError: module 'board' has no attribute 'I2C'

Any idea on how to solve it?Thank you veyr much!

**Comment by ladyada** [comment]
which board is it?

**Comment by jerryneedell** [comment]
is that an uppercase letter I (upper case i)  in board.I2C() -- just to be sure

**Comment by ame57** [comment]
I'm using either an Arduino Uno or Arduino Mega

**Comment by ladyada** [comment]
Ciruitpython isnt supported by those boards. please post up in the tech support forums of where you purchased your board, they can help you figure out what you have and get it running :)
